services:
    payment.egopay.client:
        class: vSymfo\Payment\EgoPayBundle\Client\SciClient
        arguments: [%vsymfo_payment_egopay.store_id%, %vsymfo_payment_egopay.store_password%, %vsymfo_payment_egopay.checksum_key%]

    payment.plugin.egopay:
        class: vSymfo\Payment\EgoPayBundle\Plugin\EgoPayPlugin
        arguments: [@router, @payment.egopay.client, @payment.event_dispatcher]
        tags: [{name: payment.plugin}]

    payment.form.egopay_type:
        class: vSymfo\Payment\EgoPayBundle\Form\EgoPayType
        tags:
            - {name: payment.method_form_type}
            - {name: form.type, alias: ego_pay_sci_payment}
